#!/bin/bash
# Author: Safiatu Seidu
# Date: March 14, 2026
# Description: Display 200 Linux commands with uses, numbered and colorized

# Colors
GREEN="\e[32m"
YELLOW="\e[33m"
CYAN="\e[36m"
RESET="\e[0m"

declare -A commands

# Add a subset of 200 commands (for brevity, you can expand further)
commands=(
["pwd"]="Prints the current working directory"
["ls"]="List files in a directory"
["ls -l"]="List files with detailed info"
["ls -a"]="List all files including hidden files"
["cd"]="Change directory"
["cd .."]="Move to parent directory"
["mkdir"]="Create a new directory"
["rmdir"]="Remove an empty directory"
["touch"]="Create an empty file or update timestamp"
["cp"]="Copy files or directories"
["mv"]="Move or rename files/directories"
["rm"]="Remove files"
["rm -r"]="Remove directories recursively"
["rm -f"]="Force remove files without prompt"
["cat"]="Display file contents"
["tac"]="Display file contents in reverse"
["head"]="Show first lines of a file"
["tail"]="Show last lines of a file"
["less"]="View file contents page by page"
["more"]="View file contents page by page"
["echo"]="Print text or variables to terminal"
["printf"]="Formatted printing"
["clear"]="Clear the terminal screen"
["history"]="Show command history"
["man"]="Show manual for a command"
["whatis"]="Display one-line command description"
["whereis"]="Locate binaries, source, and man pages"
["which"]="Show path of executable command"
["date"]="Show or set system date"
["cal"]="Display calendar"
["uname"]="Show system information"
["uname -a"]="Show all system information"
["hostname"]="Show system hostname"
["uptime"]="Show system uptime"
["whoami"]="Display current user"
["who"]="Show logged in users"
["w"]="Show logged in users and their activity"
["id"]="Show user and group IDs"
["groups"]="List groups of current user"
["passwd"]="Change user password"
["sudo"]="Run command as superuser"
["su"]="Switch user"
["useradd"]="Add a new user"
["userdel"]="Delete a user"
["usermod"]="Modify a user"
["groupadd"]="Add a group"
["groupdel"]="Delete a group"
["chown"]="Change file owner"
["chmod"]="Change file permissions"
["chgrp"]="Change file group"
["find"]="Search for files and directories"
["locate"]="Quickly find files using database"
["updatedb"]="Update file location database for locate"
["grep"]="Search text in files"
["egrep"]="Search with extended regex"
["awk"]="Pattern scanning and processing language"
["sed"]="Stream editor for text"
["cut"]="Extract fields or columns from text"
["sort"]="Sort lines of text"
["uniq"]="Remove duplicate lines"
["wc"]="Count lines, words, characters"
["tr"]="Translate or delete characters"
["tee"]="Redirect output to file and screen"
["xargs"]="Build and execute commands from input"
["watch"]="Run command periodically"
["sleep"]="Delay for specified seconds"
["yes"]="Repeat a string until stopped"
["alias"]="Create command shortcuts"
["unalias"]="Remove alias"
["env"]="Show environment variables"
["export"]="Set environment variable"
["set"]="Set shell options or variables"
["unset"]="Remove variables"
["printenv"]="Print environment variables"
["jobs"]="Show background jobs"
["bg"]="Resume a job in background"
["fg"]="Bring a job to foreground"
["kill"]="Terminate a process by PID"
["killall"]="Terminate processes by name"
["pkill"]="Kill process by name"
["ps"]="Show running processes"
["ps aux"]="Show all running processes with details"
["top"]="Dynamic real-time process viewer"
["htop"]="Interactive process viewer (if installed)"
["free"]="Show memory usage"
["df"]="Show disk usage"
["du"]="Show directory size"
)

# Counter
count=1

# Loop through commands and display
for cmd in "${!commands[@]}"; do
    echo -e "${CYAN}${count}. Command: ${GREEN}$cmd${RESET}"
    echo -e "   ${YELLOW}Use: ${commands[$cmd]}${RESET}"
    echo "-------------------------------------------"
    ((count++))
done
